"""initial schema

Revision ID: 32dcee0190f5
Revises: 
Create Date: 2026-09-25 13:50:37.838057
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '32dcee0190f5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('reviewer_id', sa.BigInteger(), nullable=True),
    sa.Column('reviewer_name', sa.String(length=100), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('review_message_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications'))
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_guild_id'), ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_user_id'), ['user_id'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_name', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=12), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('target', sa.String(length=200), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_guild_id'), ['guild_id'], unique=False)

    op.create_table('autoresponders',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('trigger', sa.String(length=200), nullable=False),
    sa.Column('match_type', sa.String(length=12), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('use_embed', sa.Boolean(), nullable=False),
    sa.Column('reply', sa.Boolean(), nullable=False),
    sa.Column('delete_trigger', sa.Boolean(), nullable=False),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('channel_ids', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_autoresponders'))
    )
    with op.batch_alter_table('autoresponders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_autoresponders_guild_id'), ['guild_id'], unique=False)

    op.create_table('backups',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('auto', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backups'))
    )
    with op.batch_alter_table('backups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backups_guild_id'), ['guild_id'], unique=False)

    op.create_table('badges',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('emoji', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('auto_rule', sa.String(length=20), nullable=False),
    sa.Column('rule_value', sa.String(length=64), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_badges'))
    )
    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_badges_guild_id'), ['guild_id'], unique=False)

    op.create_table('bot_state',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_bot_state'))
    )
    op.create_table('command_permissions',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('command', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('allowed_role_ids', sa.JSON(), nullable=False),
    sa.Column('denied_role_ids', sa.JSON(), nullable=False),
    sa.Column('allowed_user_ids', sa.JSON(), nullable=False),
    sa.Column('allowed_channel_ids', sa.JSON(), nullable=False),
    sa.Column('denied_channel_ids', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', 'command', name=op.f('pk_command_permissions'))
    )
    op.create_table('custom_commands',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('use_embed', sa.Boolean(), nullable=False),
    sa.Column('embed_title', sa.String(length=256), nullable=False),
    sa.Column('embed_color', sa.String(length=9), nullable=True),
    sa.Column('image_url', sa.String(length=400), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=400), nullable=True),
    sa.Column('buttons', sa.JSON(), nullable=False),
    sa.Column('ephemeral', sa.Boolean(), nullable=False),
    sa.Column('allowed_role_ids', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custom_commands')),
    sa.UniqueConstraint('guild_id', 'name', name=op.f('uq_custom_commands_guild_id'))
    )
    with op.batch_alter_table('custom_commands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_commands_guild_id'), ['guild_id'], unique=False)

    op.create_table('dashboard_sessions',
    sa.Column('id', sa.String(length=96), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('access_token_enc', sa.Text(), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dashboard_sessions'))
    )
    with op.batch_alter_table('dashboard_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dashboard_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('error_logs',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('command', sa.String(length=100), nullable=True),
    sa.Column('error_type', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('traceback', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_error_logs'))
    )
    with op.batch_alter_table('error_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_error_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_logs_guild_id'), ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_logs_resolved'), ['resolved'], unique=False)

    op.create_table('giveaways',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('prize', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('winners_count', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.BigInteger(), nullable=False),
    sa.Column('host_name', sa.String(length=100), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended', sa.Boolean(), nullable=False),
    sa.Column('requirements', sa.JSON(), nullable=False),
    sa.Column('bonus', sa.JSON(), nullable=False),
    sa.Column('winner_ids', sa.JSON(), nullable=False),
    sa.Column('image_url', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_giveaways'))
    )
    with op.batch_alter_table('giveaways', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_giveaways_ended'), ['ended'], unique=False)
        batch_op.create_index(batch_op.f('ix_giveaways_ends_at'), ['ends_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_giveaways_guild_id'), ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_giveaways_message_id'), ['message_id'], unique=False)

    op.create_table('guild_modules',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('module', sa.String(length=40), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', 'module', name=op.f('pk_guild_modules'))
    )
    op.create_table('guilds',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('next_case', sa.Integer(), nullable=False),
    sa.Column('next_ticket', sa.Integer(), nullable=False),
    sa.Column('next_suggestion', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guilds'))
    )
    op.create_table('integrations',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('data_encrypted', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', 'provider', name=op.f('pk_integrations'))
    )
    op.create_table('level_rewards',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_level_rewards'))
    )
    with op.batch_alter_table('level_rewards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_level_rewards_guild_id'), ['guild_id'], unique=False)

    op.create_table('log_entries',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('target_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_log_entries'))
    )
    with op.batch_alter_table('log_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_entries_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_entries_guild_id'), ['guild_id'], unique=False)
        batch_op.create_index('ix_log_entries_guild_time', ['guild_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_entries_user_id'), ['user_id'], unique=False)

    op.create_table('member_achievements',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', 'user_id', 'key', name=op.f('pk_member_achievements'))
    )
    op.create_table('members',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('first_joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('in_guild', sa.Boolean(), nullable=False),
    sa.Column('xp', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('last_xp_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('messages', sa.Integer(), nullable=False),
    sa.Column('voice_minutes', sa.Integer(), nullable=False),
    sa.Column('reactions', sa.Integer(), nullable=False),
    sa.Column('stream_checkins', sa.Integer(), nullable=False),
    sa.Column('events_won', sa.Integer(), nullable=False),
    sa.Column('giveaways_won', sa.Integer(), nullable=False),
    sa.Column('invites', sa.Integer(), nullable=False),
    sa.Column('invited_by', sa.BigInteger(), nullable=True),
    sa.Column('coins', sa.BigInteger(), nullable=False),
    sa.Column('coins_earned', sa.BigInteger(), nullable=False),
    sa.Column('last_coin_msg_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('daily_streak', sa.Integer(), nullable=False),
    sa.Column('daily_best_streak', sa.Integer(), nullable=False),
    sa.Column('daily_last', sa.DateTime(timezone=True), nullable=True),
    sa.Column('weekly_streak', sa.Integer(), nullable=False),
    sa.Column('weekly_last', sa.DateTime(timezone=True), nullable=True),
    sa.Column('work_last', sa.DateTime(timezone=True), nullable=True),
    sa.Column('afk_message', sa.String(length=200), nullable=True),
    sa.Column('afk_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('birthday_day', sa.Integer(), nullable=True),
    sa.Column('birthday_month', sa.Integer(), nullable=True),
    sa.Column('birthday_year', sa.Integer(), nullable=True),
    sa.Column('birthday_last_celebrated', sa.Integer(), nullable=True),
    sa.Column('profile_banner', sa.String(length=400), nullable=True),
    sa.Column('profile_bio', sa.String(length=300), nullable=True),
    sa.Column('games', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', 'user_id', name=op.f('pk_members'))
    )
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_index('ix_members_guild_coins', ['guild_id', 'coins'], unique=False)
        batch_op.create_index('ix_members_guild_xp', ['guild_id', 'xp'], unique=False)

    op.create_table('mod_cases',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('case_number', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('moderator_id', sa.BigInteger(), nullable=False),
    sa.Column('moderator_name', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mod_cases')),
    sa.UniqueConstraint('guild_id', 'case_number', name=op.f('uq_mod_cases_guild_id'))
    )
    with op.batch_alter_table('mod_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mod_cases_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_mod_cases_guild_id'), ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mod_cases_user_id'), ['user_id'], unique=False)

    op.create_table('polls',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('question', sa.String(length=300), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('multiple', sa.Boolean(), nullable=False),
    sa.Column('anonymous', sa.Boolean(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_polls'))
    )
    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_polls_ends_at'), ['ends_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_polls_guild_id'), ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_polls_message_id'), ['message_id'], unique=False)

    op.create_table('quests',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('metric', sa.String(length=20), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('reward_xp', sa.Integer(), nullable=False),
    sa.Column('reward_coins', sa.Integer(), nullable=False),
    sa.Column('reward_role_id', sa.BigInteger(), nullable=True),
    sa.Column('reward_badge_id', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quests'))
    )
    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quests_guild_id'), ['guild_id'], unique=False)

    op.create_table('raid_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('join_count', sa.Integer(), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('user_ids', sa.JSON(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raid_events'))
    )
    with op.batch_alter_table('raid_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raid_events_guild_id'), ['guild_id'], unique=False)

    op.create_table('reminders',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('remind_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reminders'))
    )
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminders_done'), ['done'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_remind_at'), ['remind_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_user_id'), ['user_id'], unique=False)

    op.create_table('role_menus',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('style', sa.String(length=10), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('max_values', sa.Integer(), nullable=False),
    sa.Column('required_role_id', sa.BigInteger(), nullable=True),
    sa.Column('color', sa.String(length=9), nullable=True),
    sa.Column('image_url', sa.String(length=400), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_menus'))
    )
    with op.batch_alter_table('role_menus', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_menus_guild_id'), ['guild_id'], unique=False)

    op.create_table('server_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('image_url', sa.String(length=400), nullable=True),
    sa.Column('reward_coins', sa.Integer(), nullable=False),
    sa.Column('reward_xp', sa.Integer(), nullable=False),
    sa.Column('reward_text', sa.String(length=200), nullable=False),
    sa.Column('reminders_sent', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_server_events'))
    )
    with op.batch_alter_table('server_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_server_events_guild_id'), ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_server_events_starts_at'), ['starts_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_server_events_status'), ['status'], unique=False)

    op.create_table('shop_items',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('emoji', sa.String(length=64), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('badge_id', sa.Integer(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('max_per_user', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop_items'))
    )
    with op.batch_alter_table('shop_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shop_items_guild_id'), ['guild_id'], unique=False)

    op.create_table('staff_notes',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('author_name', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_notes'))
    )
    with op.batch_alter_table('staff_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_notes_guild_id'), ['guild_id'], unique=False)

    op.create_table('starboard_entries',
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('star_message_id', sa.BigInteger(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('message_id', name=op.f('pk_starboard_entries'))
    )
    with op.batch_alter_table('starboard_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_starboard_entries_guild_id'), ['guild_id'], unique=False)

    op.create_table('stat_buckets',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('bucket', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric', sa.String(length=48), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', 'bucket', 'metric', name=op.f('pk_stat_buckets'))
    )
    with op.batch_alter_table('stat_buckets', schema=None) as batch_op:
        batch_op.create_index('ix_stat_buckets_metric_time', ['guild_id', 'metric', 'bucket'], unique=False)

    op.create_table('streamers',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('platform', sa.String(length=10), nullable=False),
    sa.Column('channel', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('platform_user_id', sa.String(length=64), nullable=True),
    sa.Column('avatar_url', sa.String(length=400), nullable=True),
    sa.Column('announce_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('ping_role_id', sa.BigInteger(), nullable=True),
    sa.Column('message_template', sa.Text(), nullable=False),
    sa.Column('discord_user_id', sa.BigInteger(), nullable=True),
    sa.Column('live_role_id', sa.BigInteger(), nullable=True),
    sa.Column('rename_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('rename_live', sa.String(length=100), nullable=False),
    sa.Column('rename_offline', sa.String(length=100), nullable=False),
    sa.Column('notify_videos', sa.Boolean(), nullable=False),
    sa.Column('notify_shorts', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('current_session_id', sa.Integer(), nullable=True),
    sa.Column('live_message_id', sa.BigInteger(), nullable=True),
    sa.Column('live_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('last_video_id', sa.String(length=64), nullable=True),
    sa.Column('seen_video_ids', sa.JSON(), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('subscribers', sa.Integer(), nullable=True),
    sa.Column('total_streams', sa.Integer(), nullable=False),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_streamers'))
    )
    with op.batch_alter_table('streamers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_streamers_guild_id'), ['guild_id'], unique=False)

    op.create_table('suggestions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('downvotes', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.BigInteger(), nullable=True),
    sa.Column('staff_name', sa.String(length=100), nullable=True),
    sa.Column('staff_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suggestions'))
    )
    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suggestions_guild_id'), ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestions_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestions_status'), ['status'], unique=False)

    op.create_table('temp_channels',
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('blocked_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('channel_id', name=op.f('pk_temp_channels'))
    )
    with op.batch_alter_table('temp_channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_temp_channels_guild_id'), ['guild_id'], unique=False)

    op.create_table('ticket_categories',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('emoji', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('category_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('staff_role_ids', sa.JSON(), nullable=False),
    sa.Column('modal_question', sa.String(length=45), nullable=False),
    sa.Column('welcome_message', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_categories'))
    )
    with op.batch_alter_table('ticket_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_categories_guild_id'), ['guild_id'], unique=False)

    op.create_table('user_notes',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('author_name', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_notes'))
    )
    with op.batch_alter_table('user_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_notes_guild_id'), ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_notes_user_id'), ['user_id'], unique=False)

    op.create_table('event_participants',
    sa.Column('event_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('winner', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['server_events.id'], name=op.f('fk_event_participants_event_id_server_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'user_id', name=op.f('pk_event_participants'))
    )
    op.create_table('giveaway_entries',
    sa.Column('giveaway_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('entries', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['giveaway_id'], ['giveaways.id'], name=op.f('fk_giveaway_entries_giveaway_id_giveaways'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('giveaway_id', 'user_id', name=op.f('pk_giveaway_entries'))
    )
    op.create_table('inventory',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['shop_items.id'], name=op.f('fk_inventory_item_id_shop_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory')),
    sa.UniqueConstraint('guild_id', 'user_id', 'item_id', name=op.f('uq_inventory_guild_id'))
    )
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_guild_id'), ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_user_id'), ['user_id'], unique=False)

    op.create_table('member_badges',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('badge_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('granted_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], name=op.f('fk_member_badges_badge_id_badges'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guild_id', 'user_id', 'badge_id', name=op.f('pk_member_badges'))
    )
    op.create_table('poll_votes',
    sa.Column('poll_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('option_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], name=op.f('fk_poll_votes_poll_id_polls'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('poll_id', 'user_id', 'option_index', name=op.f('pk_poll_votes'))
    )
    op.create_table('quest_progress',
    sa.Column('quest_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('period_key', sa.String(length=12), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], name=op.f('fk_quest_progress_quest_id_quests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quest_id', 'user_id', 'period_key', name=op.f('pk_quest_progress'))
    )
    with op.batch_alter_table('quest_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quest_progress_guild_id'), ['guild_id'], unique=False)

    op.create_table('stream_sessions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('streamer_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('platform_stream_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('game', sa.String(length=120), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('peak_viewers', sa.Integer(), nullable=False),
    sa.Column('viewer_sum', sa.BigInteger(), nullable=False),
    sa.Column('samples', sa.Integer(), nullable=False),
    sa.Column('checkins', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['streamer_id'], ['streamers.id'], name=op.f('fk_stream_sessions_streamer_id_streamers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stream_sessions'))
    )
    with op.batch_alter_table('stream_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stream_sessions_guild_id'), ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stream_sessions_streamer_id'), ['streamer_id'], unique=False)

    op.create_table('stream_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('streamer_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('live', sa.Boolean(), nullable=False),
    sa.Column('viewers', sa.Integer(), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('subscribers', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['streamer_id'], ['streamers.id'], name=op.f('fk_stream_snapshots_streamer_id_streamers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stream_snapshots'))
    )
    with op.batch_alter_table('stream_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_stream_snapshots_streamer_time', ['streamer_id', 'taken_at'], unique=False)

    op.create_table('suggestion_votes',
    sa.Column('suggestion_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('vote', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['suggestion_id'], ['suggestions.id'], name=op.f('fk_suggestion_votes_suggestion_id_suggestions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('suggestion_id', 'user_id', name=op.f('pk_suggestion_votes'))
    )
    op.create_table('tickets',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('category_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('category_label', sa.String(length=80), nullable=False),
    sa.Column('opener_id', sa.BigInteger(), nullable=False),
    sa.Column('opener_name', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('claimed_by', sa.BigInteger(), nullable=True),
    sa.Column('claimed_name', sa.String(length=100), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('added_user_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_response_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.BigInteger(), nullable=True),
    sa.Column('closed_by_name', sa.String(length=100), nullable=True),
    sa.Column('close_reason', sa.Text(), nullable=True),
    sa.Column('transcript_html', sa.Text(), nullable=True),
    sa.Column('transcript_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['ticket_categories.id'], name=op.f('fk_tickets_category_id_ticket_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets')),
    sa.UniqueConstraint('guild_id', 'number', name=op.f('uq_tickets_guild_id'))
    )
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tickets_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_guild_id'), ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_opener_id'), ['opener_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_status'), ['status'], unique=False)

    op.create_table('stream_checkins',
    sa.Column('session_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['stream_sessions.id'], name=op.f('fk_stream_checkins_session_id_stream_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'user_id', name=op.f('pk_stream_checkins'))
    )
    op.create_table('ticket_notes',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('author_name', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_notes_ticket_id_tickets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_notes'))
    )
    with op.batch_alter_table('ticket_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_notes_ticket_id'), ['ticket_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_notes_ticket_id'))

    op.drop_table('ticket_notes')
    op.drop_table('stream_checkins')
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_status'))
        batch_op.drop_index(batch_op.f('ix_tickets_opener_id'))
        batch_op.drop_index(batch_op.f('ix_tickets_guild_id'))
        batch_op.drop_index(batch_op.f('ix_tickets_channel_id'))

    op.drop_table('tickets')
    op.drop_table('suggestion_votes')
    with op.batch_alter_table('stream_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_stream_snapshots_streamer_time')

    op.drop_table('stream_snapshots')
    with op.batch_alter_table('stream_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stream_sessions_streamer_id'))
        batch_op.drop_index(batch_op.f('ix_stream_sessions_guild_id'))

    op.drop_table('stream_sessions')
    with op.batch_alter_table('quest_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quest_progress_guild_id'))

    op.drop_table('quest_progress')
    op.drop_table('poll_votes')
    op.drop_table('member_badges')
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_user_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_guild_id'))

    op.drop_table('inventory')
    op.drop_table('giveaway_entries')
    op.drop_table('event_participants')
    with op.batch_alter_table('user_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_notes_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_notes_guild_id'))

    op.drop_table('user_notes')
    with op.batch_alter_table('ticket_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_categories_guild_id'))

    op.drop_table('ticket_categories')
    with op.batch_alter_table('temp_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_temp_channels_guild_id'))

    op.drop_table('temp_channels')
    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suggestions_status'))
        batch_op.drop_index(batch_op.f('ix_suggestions_message_id'))
        batch_op.drop_index(batch_op.f('ix_suggestions_guild_id'))

    op.drop_table('suggestions')
    with op.batch_alter_table('streamers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_streamers_guild_id'))

    op.drop_table('streamers')
    with op.batch_alter_table('stat_buckets', schema=None) as batch_op:
        batch_op.drop_index('ix_stat_buckets_metric_time')

    op.drop_table('stat_buckets')
    with op.batch_alter_table('starboard_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_starboard_entries_guild_id'))

    op.drop_table('starboard_entries')
    with op.batch_alter_table('staff_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_notes_guild_id'))

    op.drop_table('staff_notes')
    with op.batch_alter_table('shop_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shop_items_guild_id'))

    op.drop_table('shop_items')
    with op.batch_alter_table('server_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_server_events_status'))
        batch_op.drop_index(batch_op.f('ix_server_events_starts_at'))
        batch_op.drop_index(batch_op.f('ix_server_events_guild_id'))

    op.drop_table('server_events')
    with op.batch_alter_table('role_menus', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_menus_guild_id'))

    op.drop_table('role_menus')
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminders_user_id'))
        batch_op.drop_index(batch_op.f('ix_reminders_remind_at'))
        batch_op.drop_index(batch_op.f('ix_reminders_done'))

    op.drop_table('reminders')
    with op.batch_alter_table('raid_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raid_events_guild_id'))

    op.drop_table('raid_events')
    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quests_guild_id'))

    op.drop_table('quests')
    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_polls_message_id'))
        batch_op.drop_index(batch_op.f('ix_polls_guild_id'))
        batch_op.drop_index(batch_op.f('ix_polls_ends_at'))

    op.drop_table('polls')
    with op.batch_alter_table('mod_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mod_cases_user_id'))
        batch_op.drop_index(batch_op.f('ix_mod_cases_guild_id'))
        batch_op.drop_index(batch_op.f('ix_mod_cases_action'))

    op.drop_table('mod_cases')
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index('ix_members_guild_xp')
        batch_op.drop_index('ix_members_guild_coins')

    op.drop_table('members')
    op.drop_table('member_achievements')
    with op.batch_alter_table('log_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_entries_user_id'))
        batch_op.drop_index('ix_log_entries_guild_time')
        batch_op.drop_index(batch_op.f('ix_log_entries_guild_id'))
        batch_op.drop_index(batch_op.f('ix_log_entries_category'))

    op.drop_table('log_entries')
    with op.batch_alter_table('level_rewards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_level_rewards_guild_id'))

    op.drop_table('level_rewards')
    op.drop_table('integrations')
    op.drop_table('guilds')
    op.drop_table('guild_modules')
    with op.batch_alter_table('giveaways', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_giveaways_message_id'))
        batch_op.drop_index(batch_op.f('ix_giveaways_guild_id'))
        batch_op.drop_index(batch_op.f('ix_giveaways_ends_at'))
        batch_op.drop_index(batch_op.f('ix_giveaways_ended'))

    op.drop_table('giveaways')
    with op.batch_alter_table('error_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_error_logs_resolved'))
        batch_op.drop_index(batch_op.f('ix_error_logs_guild_id'))
        batch_op.drop_index(batch_op.f('ix_error_logs_created_at'))

    op.drop_table('error_logs')
    with op.batch_alter_table('dashboard_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dashboard_sessions_user_id'))

    op.drop_table('dashboard_sessions')
    with op.batch_alter_table('custom_commands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_commands_guild_id'))

    op.drop_table('custom_commands')
    op.drop_table('command_permissions')
    op.drop_table('bot_state')
    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_badges_guild_id'))

    op.drop_table('badges')
    with op.batch_alter_table('backups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backups_guild_id'))

    op.drop_table('backups')
    with op.batch_alter_table('autoresponders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_autoresponders_guild_id'))

    op.drop_table('autoresponders')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_guild_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))

    op.drop_table('audit_log')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_user_id'))
        batch_op.drop_index(batch_op.f('ix_applications_status'))
        batch_op.drop_index(batch_op.f('ix_applications_guild_id'))

    op.drop_table('applications')
    # ### end Alembic commands ###
