"""gangs hood economy clips

Revision ID: 4bfc440f0a64
Revises: 32dcee0190f5
Create Date: 2026-09-25 15:31:26.170643
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4bfc440f0a64'
down_revision: Union[str, None] = '32dcee0190f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gangs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('tag', sa.String(length=6), nullable=False),
    sa.Column('emoji', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('leader_id', sa.BigInteger(), nullable=False),
    sa.Column('bank', sa.BigInteger(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gangs')),
    sa.UniqueConstraint('guild_id', 'name', name=op.f('uq_gangs_guild_id'))
    )
    with op.batch_alter_table('gangs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gangs_guild_id'), ['guild_id'], unique=False)

    op.create_table('gang_members',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('gang_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('rank', sa.String(length=10), nullable=False),
    sa.Column('contributed', sa.BigInteger(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gang_id'], ['gangs.id'], name=op.f('fk_gang_members_gang_id_gangs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guild_id', 'user_id', name=op.f('pk_gang_members'))
    )
    with op.batch_alter_table('gang_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gang_members_gang_id'), ['gang_id'], unique=False)

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rob_last', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('crime_last', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('streamers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_clip_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('streamers', schema=None) as batch_op:
        batch_op.drop_column('last_clip_at')

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('crime_last')
        batch_op.drop_column('rob_last')

    with op.batch_alter_table('gang_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gang_members_gang_id'))

    op.drop_table('gang_members')
    with op.batch_alter_table('gangs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gangs_guild_id'))

    op.drop_table('gangs')
    # ### end Alembic commands ###
