"""stream extras alerts predictions

Revision ID: e5b8657bbbf0
Revises: 1010607fb917
Create Date: 2026-09-27 13:41:06.767359
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e5b8657bbbf0'
down_revision: Union[str, None] = '1010607fb917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predictions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.Column('question', sa.String(length=200), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('winner', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predictions'))
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictions_guild_id'), ['guild_id'], unique=False)

    op.create_table('prediction_bets',
    sa.Column('prediction_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('option', sa.Integer(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], name=op.f('fk_prediction_bets_prediction_id_predictions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prediction_id', 'user_id', name=op.f('pk_prediction_bets'))
    )
    op.create_table('stream_alerts',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('streamer_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['streamer_id'], ['streamers.id'], name=op.f('fk_stream_alerts_streamer_id_streamers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'streamer_id', name=op.f('pk_stream_alerts'))
    )
    with op.batch_alter_table('stream_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stream_alerts_guild_id'), ['guild_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stream_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stream_alerts_guild_id'))

    op.drop_table('stream_alerts')
    op.drop_table('prediction_bets')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_guild_id'))

    op.drop_table('predictions')
    # ### end Alembic commands ###
